# Generated by Django 3.2.6 on 2021-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Title')),
                ('episode_nb', models.IntegerField(primary_key=True, serialize=False, verbose_name='Episode number')),
                ('opening_crawl', models.TextField(null=True, verbose_name='Opening crawl')),
                ('director', models.CharField(max_length=32, verbose_name='Director')),
                ('producer', models.CharField(max_length=128, verbose_name='Producer')),
                ('release_date', models.DateField(verbose_name='Release date')),
            ],
        ),
    ]
